import pg from "pg";
import { verifyToken } from "../routes/auth.js";

export const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

// Fallback in-memory state when DB is not available
export let memNextOrderNum = 46;
export let memSuppliers: any[] = [
  { id: 1, name: "أبو خالد (مورد الألعاب الرئيسية)", phone: "962775585112", notes: "توفير فوري خلال 15 دقيقة", is_active: true, created_at: new Date(Date.now() - 86400000 * 10).toISOString() },
  { id: 2, name: "شركة الألعاب العالمية (مورد الاشتراكات)", phone: "962791234567", notes: "متخصص باشتراكات بلس إكسترا وفاخر", is_active: true, created_at: new Date(Date.now() - 86400000 * 5).toISOString() }
];

export let memOrders: any[] = [
  {
    id: 101,
    order_number: "DK-00045",
    customer_name: "أحمد العبداللات",
    customer_phone: "0775589911",
    contact_whatsapp: "0775589911",
    customer_email: "ahmed.abdal@gmail.com",
    product_type: "game",
    game_name: "EA Sports FC 27",
    platform: "PS5",
    customer_paid: 38.68,
    payment_platform: "PayTabs",
    gateway_fee: 1.93,
    cost_price: null,
    status: "new",
    order_source: "paytabs",
    paytabs_tran_ref: "TST260729112233",
    items_json: JSON.stringify([{ id: "eafc27", name: "EA Sports FC 27 (PS5)", price: 38.68, quantity: 1, platform: "PS5" }]),
    notes: "طلب أونلاين عبر الموقع - دفع بطاقة إلكترونية",
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString()
  }
];

// ── DB persistence helpers with fallback memory cache ────────────────────────
const memStoreConfig = new Map<string, any>();

export async function dbLoad(key: string, defaultVal: any): Promise<any> {
  try {
    const { rows } = await pool.query("SELECT value FROM store_config WHERE key = $1", [key]);
    if (rows.length > 0) {
      memStoreConfig.set(key, rows[0].value);
      return rows[0].value;
    }
  } catch {}
  return memStoreConfig.has(key) ? memStoreConfig.get(key) : defaultVal;
}

export const dbGet = dbLoad;

export async function dbSave(key: string, value: any): Promise<void> {
  memStoreConfig.set(key, value);
  try {
    await pool.query(
      `INSERT INTO store_config (key, value, updated_at)
       VALUES ($1, $2::jsonb, NOW())
       ON CONFLICT (key) DO UPDATE SET value = $2::jsonb, updated_at = NOW()`,
      [key, JSON.stringify(value)]
    );
  } catch (_) {}
}

export function requireAdmin(req: any, res: any): boolean {
  const email = verifyToken(req.headers.authorization);
  if (!email) { res.status(401).json({ error: "غير مصرح — يرجى تسجيل الدخول كـ أدمن" }); return false; }
  return true;
}

// ── Default data ──────────────────────────────────────────────────────────────

export const DEFAULT_STORE = {
  name: "دُكانك",
  tagline: "اشتراكات وألعاب رقمية بأفضل الأسعار",
  whatsapp: "962775585112",
  whatsappDisplay: "0775585112",
  instagram: "https://www.instagram.com/dukkank15/",
};

export const DEFAULT_SUBSCRIPTIONS = [
  {
    id: "essential",
    name: "اشتراك أساسي",
    tagline: "خطط ألعاب أساسية بسعر مميز",
    accent: "blue",
    visible: true,
    durations: [
      { id: "ess-1m",  label: "شهر واحد",  four: 6.5, five: 10.0, stockStatus: "available" },
      { id: "ess-3m",  label: "٣ شهور",    four: 12,  five: 19, stockStatus: "available"   },
      { id: "ess-12m", label: "سنة كاملة", four: 24,  five: 48, stockStatus: "available"   },
    ],
  },
  {
    id: "extra",
    name: "اشتراك إضافي",
    tagline: "تجربة أوسع مع مكتبة ألعاب أكبر",
    accent: "red",
    visible: true,
    durations: [
      { id: "ext-1m",  label: "شهر واحد",  four: 9,  five: 14.0, stockStatus: "available" },
      { id: "ext-3m",  label: "٣ شهور",    four: 19, five: 28, stockStatus: "available"   },
      { id: "ext-12m", label: "سنة كاملة", four: 42, five: 59, stockStatus: "available"   },
    ],
  },
  {
    id: "deluxe",
    name: "بلايستيشن بلس فاخر",
    tagline: "الباقة الملكية والشاملة لكافة الألعاب الكلاسيكية والتجريبية",
    accent: "amber",
    visible: true,
    durations: [
      { id: "del-1m",  label: "شهر واحد",  four: 11, five: 16, stockStatus: "available" },
      { id: "del-3m",  label: "٣ شهور",    four: 22, five: 33, stockStatus: "available" },
      { id: "del-12m", label: "سنة كاملة", four: 49, five: 69, stockStatus: "available" },
    ],
  },
];

export const DEFAULT_GAMES = [
  {
    "id": "arc-raiders",
    "name": "Arc Raiders",
    "sub": "تصويب وخيال علمي • مغامرة بقاء أسطورية",
    "image": "/games/arc-raiders.jpg",
    "gradientFrom": "#2a3340",
    "gradientTo": "#0a0e14",
    "four": null,
    "five": 22.82,
    "secondary": 14.41,
    "costFour": null,
    "costFive": 16.82,
    "costSecondary": 8.41,
    "available": true,
    "bestSeller": false,
    "order": 0
  },
  {
    "id": "ac-mirage",
    "name": "Assassin's Creed Mirage (عربي)",
    "sub": "تخفي وأكشن • بالدبلجة والترجمة العربية في بغداد",
    "image": "/games/ac-mirage.jpg",
    "gradientFrom": "#4a3010",
    "gradientTo": "#140a04",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 1
  },
  {
    "id": "ac-origins",
    "name": "Assassin's Creed Origins",
    "sub": "عالم مفتوح • أساطير الفراعنة في مصر القديمة",
    "image": "/games/ac-origins.jpg",
    "gradientFrom": "#4a3b10",
    "gradientTo": "#140e02",
    "four": 8.8,
    "five": 9.74,
    "secondary": 7.87,
    "costFour": 2.8,
    "costFive": 3.74,
    "costSecondary": 1.87,
    "available": true,
    "bestSeller": false,
    "order": 2
  },
  {
    "id": "ac-shadows",
    "name": "Assassin's Creed Shadows",
    "sub": "ساموراي ونينجا • ملحمة اليابان الإقطاعية الجديدة",
    "image": "/games/ac-shadows.jpg",
    "gradientFrom": "#3a0d10",
    "gradientTo": "#0f0304",
    "four": null,
    "five": 29.36,
    "secondary": 21.89,
    "costFour": null,
    "costFive": 23.36,
    "costSecondary": 15.89,
    "available": true,
    "bestSeller": false,
    "order": 3
  },
  {
    "id": "ac-valhalla",
    "name": "Assassin's Creed Valhalla",
    "sub": "فايكنج وعالم مفتوح • حروب وغزوات إنجلترا",
    "image": "/games/ac-valhalla.jpg",
    "gradientFrom": "#1b3a30",
    "gradientTo": "#07120e",
    "four": 11.14,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 5.14,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 4
  },
  {
    "id": "astrobot",
    "name": "Astro Bot",
    "sub": "مغامرات ومنصات • لعبة السنة والأعلى تقييماً",
    "image": "/games/astrobot.jpg",
    "gradientFrom": "#103a5a",
    "gradientTo": "#03111f",
    "four": null,
    "five": 31.23,
    "secondary": 21.89,
    "costFour": null,
    "costFive": 25.23,
    "costSecondary": 15.89,
    "available": true,
    "bestSeller": false,
    "order": 5
  },
  {
    "id": "away-out",
    "name": "A Way Out",
    "sub": "تعاوني ثنائي • خطة الهروب من السجن",
    "image": "/games/away-out.jpg",
    "gradientFrom": "#2d241e",
    "gradientTo": "#0e0a07",
    "four": 9.74,
    "five": 10.67,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 4.67,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 6
  },
  {
    "id": "batman-arkham",
    "name": "Batman: Arkham Collection",
    "sub": "أكشن وأبطال خارقين • ثلاثية باتمان الأسطورية",
    "image": "/games/batman-arkham.jpg",
    "gradientFrom": "#18202c",
    "gradientTo": "#06090d",
    "four": 9.74,
    "five": 12.54,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 6.54,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 7
  },
  {
    "id": "battlefield6",
    "name": "Battlefield 6",
    "sub": "حروب ضخمة • الجيل القادم من المعارك الشاملة",
    "image": "/games/bf6.jpg",
    "gradientFrom": "#3d2a14",
    "gradientTo": "#160e05",
    "four": null,
    "five": 34.04,
    "secondary": 21.89,
    "costFour": null,
    "costFive": 28.04,
    "costSecondary": 15.89,
    "available": true,
    "bestSeller": false,
    "order": 8
  },
  {
    "id": "blackops3",
    "name": "Call of Duty: Black Ops 3",
    "sub": "تصويب مستقبلي • طور الزومبي واللعب الجماعي",
    "image": "/games/blackops3.jpg",
    "gradientFrom": "#3a200a",
    "gradientTo": "#120902",
    "four": 14.41,
    "five": 16.28,
    "secondary": 12.54,
    "costFour": 8.41,
    "costFive": 10.28,
    "costSecondary": 6.54,
    "available": true,
    "bestSeller": false,
    "order": 9
  },
  {
    "id": "blackops4",
    "name": "Call of Duty: Black Ops 4",
    "sub": "أكشن وتصويب • باتل رويال وطور الزومبي",
    "image": "/games/blackops4.jpg",
    "gradientFrom": "#3a1508",
    "gradientTo": "#120502",
    "four": 9.74,
    "five": 10.67,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 4.67,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 10
  },
  {
    "id": "blackops6",
    "name": "Call of Duty: Black Ops 6",
    "sub": "تصويب وحرب • طور القصة واللعب الجماعي",
    "image": "/games/blackops6.jpg",
    "gradientFrom": "#1f2310",
    "gradientTo": "#080a04",
    "four": 14.41,
    "five": 24.69,
    "secondary": 16.28,
    "costFour": 8.41,
    "costFive": 18.69,
    "costSecondary": 10.28,
    "available": true,
    "bestSeller": false,
    "order": 11
  },
  {
    "id": "blackops7",
    "name": "Call of Duty: Black Ops 7",
    "sub": "تصويب ملحمي • أحدث إصدارات سلسلة بلاك أوبس",
    "image": "/games/blackops7.jpg",
    "gradientFrom": "#2a2f1a",
    "gradientTo": "#0d0f08",
    "four": 16.28,
    "five": 36.84,
    "secondary": 15.35,
    "costFour": 10.28,
    "costFive": 30.84,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": true,
    "order": 12
  },
  {
    "id": "cod-coldwar",
    "name": "Call of Duty: Black Ops Cold War",
    "sub": "الحرب الباردة • طور القصة والزومبي",
    "image": "/games/cod-coldwar.jpg",
    "gradientFrom": "#202a35",
    "gradientTo": "#080d13",
    "four": 14.41,
    "five": 17.21,
    "secondary": 12.54,
    "costFour": 8.41,
    "costFive": 11.21,
    "costSecondary": 6.54,
    "available": true,
    "bestSeller": false,
    "order": 13
  },
  {
    "id": "cod-mwii",
    "name": "Call of Duty: Modern Warfare II",
    "sub": "عمليات خاصة • فرقة Task Force 141",
    "image": "/games/cod-mwii.jpg",
    "gradientFrom": "#152c1a",
    "gradientTo": "#051108",
    "four": 16.28,
    "five": 20.02,
    "secondary": 15.35,
    "costFour": 10.28,
    "costFive": 14.02,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 14
  },
  {
    "id": "cod-mwiii",
    "name": "Call of Duty: Modern Warfare III",
    "sub": "حرب حديثة • مواجهة ماكاروف وأطوار اللعب",
    "image": "/games/cod-mwiii.jpg",
    "gradientFrom": "#3a1010",
    "gradientTo": "#120303",
    "four": 16.28,
    "five": 20.02,
    "secondary": 15.35,
    "costFour": 10.28,
    "costFive": 14.02,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 15
  },
  {
    "id": "cod-wwii",
    "name": "Call of Duty: WWII",
    "sub": "الحرب العالمية الثانية • معارك نورماندي التاريخية",
    "image": "/games/cod-wwii.jpg",
    "gradientFrom": "#2e2418",
    "gradientTo": "#0f0b07",
    "four": 10.67,
    "five": 10.67,
    "secondary": 9.27,
    "costFour": 4.67,
    "costFive": 4.67,
    "costSecondary": 3.27,
    "available": true,
    "bestSeller": false,
    "order": 16
  },
  {
    "id": "crash-ctr",
    "name": "Crash Bandicoot Trilogy + CTR",
    "sub": "مغامرات وسباقات • كراش بانديكوت + سباق السيارات",
    "image": "/games/crash-ctr.jpg",
    "gradientFrom": "#4a2808",
    "gradientTo": "#140a02",
    "four": 10.67,
    "five": 12.54,
    "secondary": 8.8,
    "costFour": 4.67,
    "costFive": 6.54,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 17
  },
  {
    "id": "crew-motorfest",
    "name": "The Crew Motorfest",
    "sub": "سباقات وعالم مفتوح • جزيرة هاواي ومهرجان السرعة",
    "image": "/games/crew-motorfest.jpg",
    "gradientFrom": "#1a4f7a",
    "gradientTo": "#04161f",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 18
  },
  {
    "id": "crimson-desert",
    "name": "Crimson Desert",
    "sub": "مغامرات وعالم مفتوح RPG • رسومات الجيل القادم",
    "image": "/games/crimson-desert.jpg",
    "gradientFrom": "#3d1f14",
    "gradientTo": "#130905",
    "four": null,
    "five": 39.64,
    "secondary": 28.43,
    "costFour": null,
    "costFive": 33.64,
    "costSecondary": 22.43,
    "available": true,
    "bestSeller": false,
    "order": 19
  },
  {
    "id": "cyberpunk",
    "name": "Cyberpunk 2077",
    "sub": "عالم مفتوح وخيال علمي • مدينة نايت سيتي المستقبلية",
    "image": "/games/cyberpunk.jpg",
    "gradientFrom": "#4a3d08",
    "gradientTo": "#141002",
    "four": 14.41,
    "five": 20.02,
    "secondary": 16.28,
    "costFour": 8.41,
    "costFive": 14.02,
    "costSecondary": 10.28,
    "available": true,
    "bestSeller": false,
    "order": 20
  },
  {
    "id": "days-gone",
    "name": "Days Gone Remastered",
    "sub": "بقاء وعالم مفتوح • مواجهة جحافل الزومبي بالدراجة",
    "image": "/games/days-gone.jpg",
    "gradientFrom": "#262b20",
    "gradientTo": "#090d07",
    "four": 16.28,
    "five": 20.02,
    "secondary": 14.41,
    "costFour": 10.28,
    "costFive": 14.02,
    "costSecondary": 8.41,
    "available": true,
    "bestSeller": false,
    "order": 21
  },
  {
    "id": "darwins-paradox",
    "name": "Darwin's Paradox",
    "sub": "أكشن وخيال علمي • مغامرة الجيل الجديد",
    "image": "/games/darwins-paradox.jpg",
    "gradientFrom": "#102f3a",
    "gradientTo": "#030f14",
    "four": null,
    "five": 24.69,
    "secondary": 15.35,
    "costFour": null,
    "costFive": 18.69,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 22
  },
  {
    "id": "detroit",
    "name": "Detroit: Become Human (عربي)",
    "sub": "قصة وتفاعل سينمائي • بالدبلجة والترجمة العربية",
    "image": "/games/detroit.jpg",
    "gradientFrom": "#14283d",
    "gradientTo": "#040e17",
    "four": 12.54,
    "five": 13.48,
    "secondary": 11.61,
    "costFour": 6.54,
    "costFive": 7.48,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": false,
    "order": 23
  },
  {
    "id": "elden-nightreign",
    "name": "Elden Ring: Nightreign",
    "sub": "سولز وعالم مفتوح • التوسعة والمغامرة الكبرى",
    "image": "/games/elden-nightreign.jpg",
    "gradientFrom": "#2c1c0a",
    "gradientTo": "#0d0702",
    "four": 17.21,
    "five": 20.02,
    "secondary": 15.35,
    "costFour": 11.21,
    "costFive": 14.02,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 24
  },
  {
    "id": "elden-ring",
    "name": "Elden Ring (عربي)",
    "sub": "سولز وملحمة خيالية • الفائزة بجائزة لعبة السنة",
    "image": "/games/elden-ring.jpg",
    "gradientFrom": "#3a2710",
    "gradientTo": "#100905",
    "four": 18.15,
    "five": 22.82,
    "secondary": 20.02,
    "costFour": 12.15,
    "costFive": 16.82,
    "costSecondary": 14.02,
    "available": true,
    "bestSeller": true,
    "order": 25
  },
  {
    "id": "f1",
    "name": "EA Sports F1",
    "sub": "سباقات فورمولا 1 • محاكاة بطولة العالم الرسمية",
    "image": "/games/f1.jpg",
    "gradientFrom": "#4a1010",
    "gradientTo": "#120202",
    "four": null,
    "five": 26.56,
    "secondary": 20.02,
    "costFour": null,
    "costFive": 20.56,
    "costSecondary": 14.02,
    "available": true,
    "bestSeller": false,
    "order": 26
  },
  {
    "id": "farcry6",
    "name": "Far Cry 6",
    "sub": "أكشن وعالم مفتوح • الثورة في جزيرة يارا",
    "image": "/games/farcry6.jpg",
    "gradientFrom": "#402d10",
    "gradientTo": "#120c03",
    "four": 11.23,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 5.23,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 27
  },
  {
    "id": "eafc26",
    "name": "EA Sports FC 26",
    "sub": "كرة القدم الأولى عالمياً • Ultimate Team و Career Mode",
    "image": "/games/eafc26.jpg",
    "gradientFrom": "#1c5e3a",
    "gradientTo": "#0f2e1c",
    "four": 14.41,
    "five": 21.89,
    "secondary": 12.54,
    "costFour": 8.41,
    "costFive": 15.89,
    "costSecondary": 6.54,
    "available": true,
    "bestSeller": true,
    "order": 28
  },
  {
    "id": "forza5",
    "name": "Forza Horizon 5",
    "sub": "سباقات وعالم مفتوح • أضخم مهرجان سيارات في المكسيك",
    "image": "/games/forza5.jpg",
    "gradientFrom": "#0d3a4a",
    "gradientTo": "#031018",
    "four": null,
    "five": 26.56,
    "secondary": 19.08,
    "costFour": null,
    "costFive": 20.56,
    "costSecondary": 13.08,
    "available": true,
    "bestSeller": true,
    "order": 29
  },
  {
    "id": "gang-beasts",
    "name": "Gang Beasts",
    "sub": "قتال كوميدي ومرح • لعب جماعي ممتع مع الأصدقاء",
    "image": "/games/gang-beasts.jpg",
    "gradientFrom": "#3a1435",
    "gradientTo": "#120410",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 30
  },
  {
    "id": "ghost-tsushima",
    "name": "Ghost of Tsushima (عربي)",
    "sub": "ساموراي وعالم مفتوح • بالدبلجة والترجمة العربية",
    "image": "/games/ghost-tsushima.jpg",
    "gradientFrom": "#5a1010",
    "gradientTo": "#1a0405",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": true,
    "order": 31
  },
  {
    "id": "ghost-yotei",
    "name": "Ghost of Yōtei",
    "sub": "ملحمة الساموراي الجديدة • استكشاف جبل يوتي الأسطوري",
    "image": "/games/ghost-yotei.jpg",
    "gradientFrom": "#3a0d0d",
    "gradientTo": "#120303",
    "four": null,
    "five": 39.64,
    "secondary": 29.36,
    "costFour": null,
    "costFive": 33.64,
    "costSecondary": 23.36,
    "available": true,
    "bestSeller": false,
    "order": 32
  },
  {
    "id": "gow3",
    "name": "God of War III Remastered",
    "sub": "أكشن وملاحم إغريقية • مغامرة كريتوس الأسطورية",
    "image": "/games/gow3.jpg",
    "gradientFrom": "#3a1510",
    "gradientTo": "#120504",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 33
  },
  {
    "id": "gow4",
    "name": "God of War (2018)",
    "sub": "مغامرات وأساطير الشمال • رحلة كريتوس وأتريوس",
    "image": "/games/gow4.jpg",
    "gradientFrom": "#202c3a",
    "gradientTo": "#080e14",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 34
  },
  {
    "id": "gow-ragnarok",
    "name": "God of War Ragnarök",
    "sub": "معركة راجناروك الكبرى • النسخة الأساسية",
    "image": "/games/gow-ragnarok.jpg",
    "gradientFrom": "#1b2a3d",
    "gradientTo": "#060c14",
    "four": 18.15,
    "five": 21.89,
    "secondary": 16.28,
    "costFour": 12.15,
    "costFive": 15.89,
    "costSecondary": 10.28,
    "available": true,
    "bestSeller": true,
    "order": 35
  },
  {
    "id": "gow-ragnarok-deluxe",
    "name": "God of War Ragnarök (Deluxe)",
    "sub": "النسخة الفاخرة • مع كافة الدروع والمظاهر الإضافية",
    "image": "/games/gow-ragnarok.jpg",
    "gradientFrom": "#2d1c3a",
    "gradientTo": "#0d0612",
    "four": 20.02,
    "five": 26.56,
    "secondary": 17.21,
    "costFour": 14.02,
    "costFive": 20.56,
    "costSecondary": 11.21,
    "available": true,
    "bestSeller": false,
    "order": 36
  },
  {
    "id": "gt7",
    "name": "Gran Turismo 7",
    "sub": "محاكي القيادة الحقيقي • أحدث السيارات وحلبات السباق",
    "image": "/games/gt7.jpg",
    "gradientFrom": "#10253d",
    "gradientTo": "#030a12",
    "four": 18.15,
    "five": 21.89,
    "secondary": 15.35,
    "costFour": 12.15,
    "costFive": 15.89,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 37
  },
  {
    "id": "gta5",
    "name": "Grand Theft Auto V",
    "sub": "عالم مفتوح وأكشن • النسخة المحسنة + GTA Online",
    "image": "/games/gta5.jpg",
    "gradientFrom": "#13343f",
    "gradientTo": "#04141a",
    "four": 13.48,
    "five": 17.21,
    "secondary": 11.61,
    "costFour": 7.48,
    "costFive": 11.21,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": true,
    "order": 38
  },
  {
    "id": "hitman-woa",
    "name": "Hitman: World of Assassination",
    "sub": "تخفي واغتيالات • الثلاثية الكاملة للعميل 47",
    "image": "/games/hitman-woa.jpg",
    "gradientFrom": "#202020",
    "gradientTo": "#070707",
    "four": 17.21,
    "five": 21.89,
    "secondary": 15.35,
    "costFour": 11.21,
    "costFive": 15.89,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 39
  },
  {
    "id": "hogwarts",
    "name": "Hogwarts Legacy Deluxe (عربي)",
    "sub": "عالم هاري بوتر السحري • النسخة الفاخرة مع الترجمة",
    "image": "/games/hogwarts.jpg",
    "gradientFrom": "#2a1e38",
    "gradientTo": "#0d0714",
    "four": 12.54,
    "five": 14.41,
    "secondary": 11.61,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": false,
    "order": 40
  },
  {
    "id": "hollow-knight",
    "name": "Hollow Knight",
    "sub": "مغامرات وميترويدفينيا • تحفة فنية واستكشاف ممتع",
    "image": "/games/hollow-knight.jpg",
    "gradientFrom": "#15202e",
    "gradientTo": "#05080d",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 41
  },
  {
    "id": "horizon-fw",
    "name": "Horizon Forbidden West",
    "sub": "عالم مفتوح ومستقبل آلي • رحلة إيلوي للغرب المحظور",
    "image": "/games/horizon-fw.jpg",
    "gradientFrom": "#143a3d",
    "gradientTo": "#031214",
    "four": 16.28,
    "five": 20.02,
    "secondary": 15.35,
    "costFour": 10.28,
    "costFive": 14.02,
    "costSecondary": 9.35,
    "available": true,
    "bestSeller": false,
    "order": 42
  },
  {
    "id": "injustice2",
    "name": "Injustice 2",
    "sub": "قتال وأبطال DC • باتمان وسوبرمان وبقية الأبطال",
    "image": "/games/injustice2.jpg",
    "gradientFrom": "#1a2a3a",
    "gradientTo": "#060c12",
    "four": 9.74,
    "five": 9.74,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 3.74,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 43
  },
  {
    "id": "it-takes-two",
    "name": "It Takes Two",
    "sub": "مغامرة تعاونية ثنائية • الفائزة بجائزة لعبة السنة",
    "image": "/games/it-takes-two.jpg",
    "gradientFrom": "#402010",
    "gradientTo": "#140803",
    "four": 10.67,
    "five": 13.48,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 7.48,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 44
  },
  {
    "id": "tlou1",
    "name": "The Last of Us Part I",
    "sub": "مغامرة البقاء الخالدة • ريميك الجيل الجديد لقصة جول وإيلي",
    "image": "/games/tlou1.jpg",
    "gradientFrom": "#1d2a18",
    "gradientTo": "#070a05",
    "four": 10.67,
    "five": 10.67,
    "secondary": 8.8,
    "costFour": 4.67,
    "costFive": 4.67,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": true,
    "order": 45
  },
  {
    "id": "tlou2",
    "name": "The Last of Us Part II",
    "sub": "دراما وبقاء ملحمي • النسخة الأساسية المحسنة",
    "image": "/games/tlou2.jpg",
    "gradientFrom": "#2c2415",
    "gradientTo": "#0c0a05",
    "four": 18.15,
    "five": 20.02,
    "secondary": 14.41,
    "costFour": 12.15,
    "costFive": 14.02,
    "costSecondary": 8.41,
    "available": true,
    "bestSeller": true,
    "order": 46
  },
  {
    "id": "tlou2-deluxe",
    "name": "The Last of Us Part II Deluxe",
    "sub": "النسخة الفاخرة • مع كافة الإضافات والترقيات",
    "image": "/games/tlou2.jpg",
    "gradientFrom": "#381e15",
    "gradientTo": "#120805",
    "four": 20.02,
    "five": 21.89,
    "secondary": 16.28,
    "costFour": 14.02,
    "costFive": 15.89,
    "costSecondary": 10.28,
    "available": true,
    "bestSeller": false,
    "order": 47
  },
  {
    "id": "little-nightmares3",
    "name": "Little Nightmares III",
    "sub": "رعب ومغامرات ألغاز • تجربة تعاونية مشوقة",
    "image": "/games/little-nightmares3.jpg",
    "gradientFrom": "#2e2410",
    "gradientTo": "#0d0903",
    "four": 13.48,
    "five": 17.21,
    "secondary": 11.61,
    "costFour": 7.48,
    "costFive": 11.21,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": false,
    "order": 48
  },
  {
    "id": "mafia-trilogy",
    "name": "Mafia: Trilogy",
    "sub": "عالم الجريمة والمافيا • الثلاثية الكاملة المحسنة",
    "image": "/games/mafia-trilogy.jpg",
    "gradientFrom": "#3a1515",
    "gradientTo": "#120404",
    "four": 10.67,
    "five": 10.67,
    "secondary": 8.8,
    "costFour": 4.67,
    "costFive": 4.67,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 49
  },
  {
    "id": "minecraft",
    "name": "Minecraft",
    "sub": "بناء وعالم لا نهائي • استكشف وابنِ عوالمك بلا حدود",
    "image": "/games/minecraft.jpg",
    "gradientFrom": "#203a18",
    "gradientTo": "#081205",
    "four": 12.54,
    "five": 14.41,
    "secondary": 11.61,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": true,
    "order": 50
  },
  {
    "id": "mk1",
    "name": "Mortal Kombat 1",
    "sub": "قتال وحركات قاضية دموية • إعادة بناء عالم مورتال كومبات",
    "image": "/games/mk1.jpg",
    "gradientFrom": "#3a1410",
    "gradientTo": "#120403",
    "four": null,
    "five": 18.15,
    "secondary": 12.54,
    "costFour": null,
    "costFive": 12.15,
    "costSecondary": 6.54,
    "available": true,
    "bestSeller": false,
    "order": 51
  },
  {
    "id": "mk11",
    "name": "Mortal Kombat 11",
    "sub": "قتال وحماس • النسخة المحسنة مع كامل الشخصيات",
    "image": "/games/mk11.jpg",
    "gradientFrom": "#3a1a08",
    "gradientTo": "#120602",
    "four": 9.74,
    "five": 9.74,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 3.74,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 52
  },
  {
    "id": "nba2k26",
    "name": "NBA 2K26",
    "sub": "كرة السلة الأمريكية • محاكاة واقعية مع نجوم الدوري",
    "image": "/games/nba2k26.webp",
    "gradientFrom": "#3a1820",
    "gradientTo": "#120508",
    "four": 15.35,
    "five": 20.02,
    "secondary": 13.48,
    "costFour": 9.35,
    "costFive": 14.02,
    "costSecondary": 7.48,
    "available": true,
    "bestSeller": false,
    "order": 53
  },
  {
    "id": "nfs-heat",
    "name": "Need for Speed Heat",
    "sub": "سباقات شوارع ومطاردات شرطة • سباقات ليلية حماسية",
    "image": "/games/nfs-heat.jpg",
    "gradientFrom": "#3d1030",
    "gradientTo": "#12030f",
    "four": 9.74,
    "five": 9.74,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 3.74,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 54
  },
  {
    "id": "overcooked",
    "name": "Overcooked! All You Can Eat (1+2)",
    "sub": "طبخ وفوضى عائلية • الجزئين 1 و 2 مع كامل الإضافات",
    "image": "/games/overcooked.jpg",
    "gradientFrom": "#3a2a10",
    "gradientTo": "#120c03",
    "four": 10.67,
    "five": 12.54,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 6.54,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 55
  },
  {
    "id": "overcooked2",
    "name": "Overcooked! 2",
    "sub": "طبخ جماعي وتحديات • متعة وتنسيق مع الأصدقاء",
    "image": "/games/overcooked2.jpg",
    "gradientFrom": "#2e3a15",
    "gradientTo": "#0d1204",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 56
  },
  {
    "id": "pes2019",
    "name": "eFootball PES 2019",
    "sub": "كرة قدم كلاسيكية • النسخة التاريخية المفضلة",
    "image": "/games/pes2019.jpg",
    "gradientFrom": "#15253a",
    "gradientTo": "#050b12",
    "four": 26.56,
    "five": 30.3,
    "secondary": 22.82,
    "costFour": 20.56,
    "costFive": 24.3,
    "costSecondary": 16.82,
    "available": true,
    "bestSeller": false,
    "order": 57
  },
  {
    "id": "pes2021",
    "name": "eFootball PES 2021 Season Update",
    "sub": "كرة قدم واقعية • التحديث الأسطوري لقوائم الفرق",
    "image": "/games/pes2021.jpg",
    "gradientFrom": "#1a3045",
    "gradientTo": "#06101a",
    "four": 21.89,
    "five": 26.56,
    "secondary": 19.08,
    "costFour": 15.89,
    "costFive": 20.56,
    "costSecondary": 13.08,
    "available": true,
    "bestSeller": true,
    "order": 58
  },
  {
    "id": "ratchet-clank",
    "name": "Ratchet & Clank: Rift Apart",
    "sub": "مغامرات وتنقل أبعاد • تجربة حصرية لاستعراض قوة PS5",
    "image": "/games/ratchet-clank.jpg",
    "gradientFrom": "#251838",
    "gradientTo": "#0b0512",
    "four": null,
    "five": 14.41,
    "secondary": 11.61,
    "costFour": null,
    "costFive": 8.41,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": false,
    "order": 59
  },
  {
    "id": "rayman",
    "name": "Rayman Legends",
    "sub": "منصات ومرح عائلي • واحدة من أفضل ألعاب المنصات",
    "image": "/games/rayman.jpg",
    "gradientFrom": "#3a2c10",
    "gradientTo": "#120c03",
    "four": 9.27,
    "five": 10.21,
    "secondary": 8.8,
    "costFour": 3.27,
    "costFive": 4.21,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 60
  },
  {
    "id": "ready-or-not",
    "name": "Ready or Not",
    "sub": "اقتحام وتكتيك SWAT • واقعية قتالية عالية جداً",
    "image": "/games/ready-or-not.jpg",
    "gradientFrom": "#1a1a1a",
    "gradientTo": "#050505",
    "four": null,
    "five": 28.43,
    "secondary": 21.89,
    "costFour": null,
    "costFive": 22.43,
    "costSecondary": 15.89,
    "available": true,
    "bestSeller": false,
    "order": 61
  },
  {
    "id": "reanimal",
    "name": "Reanimal",
    "sub": "رعب نفسي ومغامرات مظلمة • من مطوري ليتل نايتميرز",
    "image": "/games/reanimal.jpg",
    "gradientFrom": "#252015",
    "gradientTo": "#0b0904",
    "four": null,
    "five": 22.82,
    "secondary": 19.08,
    "costFour": null,
    "costFive": 16.82,
    "costSecondary": 13.08,
    "available": true,
    "bestSeller": false,
    "order": 62
  },
  {
    "id": "re2",
    "name": "Resident Evil 2 Remake",
    "sub": "رعب وبقاء • كابوس مدينة راكون مع ليون وكلير",
    "image": "/games/re2.jpg",
    "gradientFrom": "#3a1010",
    "gradientTo": "#120303",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 63
  },
  {
    "id": "re3",
    "name": "Resident Evil 3 Remake",
    "sub": "هروب ورعب • مواجهة الوحش نيمسيس",
    "image": "/games/re3.jpg",
    "gradientFrom": "#301515",
    "gradientTo": "#100404",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 64
  },
  {
    "id": "rdr2",
    "name": "Red Dead Redemption 2",
    "sub": "ملحمة الغرب الأمريكي • آرثر مورغان وعصابة فان دير ليند",
    "image": "/games/rdr2.jpg",
    "gradientFrom": "#4a2412",
    "gradientTo": "#180a04",
    "four": 11.61,
    "five": 14.41,
    "secondary": 9.74,
    "costFour": 5.61,
    "costFive": 8.41,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": true,
    "order": 65
  },
  {
    "id": "re4",
    "name": "Resident Evil 4 Remake",
    "sub": "ريميك أسطوري • إنقاذ ابنة الرئيس في قرية الرعب",
    "image": "/games/re4.jpg",
    "gradientFrom": "#351a10",
    "gradientTo": "#100603",
    "four": 12.54,
    "five": 15.35,
    "secondary": 11.61,
    "costFour": 6.54,
    "costFive": 9.35,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": true,
    "order": 66
  },
  {
    "id": "re4-gold",
    "name": "Resident Evil 4 Gold Edition",
    "sub": "النسخة الذهبية • مع إضافة Separate Ways وكامل الإضافات",
    "image": "/games/re4-gold.jpg",
    "gradientFrom": "#4a3510",
    "gradientTo": "#140e03",
    "four": 14.41,
    "five": 18.15,
    "secondary": 12.54,
    "costFour": 8.41,
    "costFive": 12.15,
    "costSecondary": 6.54,
    "available": true,
    "bestSeller": false,
    "order": 67
  },
  {
    "id": "re9",
    "name": "Resident Evil 9 - Requiem",
    "sub": "الإصدار الأحدث والأضخم • كابوس جديد لأسطورة الرعب",
    "image": "/games/re9.jpg",
    "gradientFrom": "#4a0e0e",
    "gradientTo": "#1a0303",
    "four": null,
    "five": 40.58,
    "secondary": 31.23,
    "costFour": null,
    "costFive": 34.58,
    "costSecondary": 25.23,
    "available": true,
    "bestSeller": false,
    "order": 68
  },
  {
    "id": "re7",
    "name": "Resident Evil 7: Biohazard",
    "sub": "رعب منظور أول • قصر عائلة بيكر المرعب",
    "image": "/games/re7.jpg",
    "gradientFrom": "#2a2012",
    "gradientTo": "#0d0a04",
    "four": 10.67,
    "five": 11.61,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 69
  },
  {
    "id": "re8",
    "name": "Resident Evil Village (RE8)",
    "sub": "رعب وقلاع مصاصي الدماء • قصة إيثان وينترز",
    "image": "/games/re8.jpg",
    "gradientFrom": "#2a1010",
    "gradientTo": "#0a0202",
    "four": 10.67,
    "five": 12.54,
    "secondary": 9.74,
    "costFour": 4.67,
    "costFive": 6.54,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 70
  },
  {
    "id": "re8-gold",
    "name": "Resident Evil Village (Gold)",
    "sub": "النسخة الذهبية • طور المنظور الثالث وإضافة روز",
    "image": "/games/re8-gold.jpg",
    "gradientFrom": "#422810",
    "gradientTo": "#140c03",
    "four": 12.54,
    "five": 16.28,
    "secondary": 11.61,
    "costFour": 6.54,
    "costFive": 10.28,
    "costSecondary": 5.61,
    "available": true,
    "bestSeller": false,
    "order": 71
  },
  {
    "id": "sekiro",
    "name": "Sekiro: Shadows Die Twice",
    "sub": "ساموراي وصعوبة وتحدي • الفائزة بجائزة لعبة السنة",
    "image": "/games/sekiro.jpg",
    "gradientFrom": "#3a1e10",
    "gradientTo": "#120803",
    "four": 11.61,
    "five": 12.54,
    "secondary": 9.74,
    "costFour": 5.61,
    "costFive": 6.54,
    "costSecondary": 3.74,
    "available": true,
    "bestSeller": false,
    "order": 72
  },
  {
    "id": "silksong",
    "name": "Hollow Knight: Silksong",
    "sub": "مغامرات ومنصات • رحلة هورنيت في المملكة الجديدة",
    "image": "/games/silksong.jpg",
    "gradientFrom": "#3a1520",
    "gradientTo": "#120408",
    "four": 14.41,
    "five": 18.15,
    "secondary": 13.48,
    "costFour": 8.41,
    "costFive": 12.15,
    "costSecondary": 7.48,
    "available": true,
    "bestSeller": false,
    "order": 73
  },
  {
    "id": "spiderman2",
    "name": "Marvel's Spider-Man 2 (عربي)",
    "sub": "أكشن ومغامرات • بيتر باركر ومايلز موراليس بالعربي",
    "image": "/games/spiderman2.jpg",
    "gradientFrom": "#5a0a0a",
    "gradientTo": "#1d0306",
    "four": null,
    "five": 28.43,
    "secondary": 20.95,
    "costFour": null,
    "costFive": 22.43,
    "costSecondary": 14.95,
    "available": true,
    "bestSeller": true,
    "order": 74
  },
  {
    "id": "spiderman-marvel",
    "name": "Marvel's Spider-Man Remastered",
    "sub": "مغامرات نيويورك • النسخة المحسنة الأولى لسبايدرمان",
    "image": "/games/spiderman-marvel.jpg",
    "gradientFrom": "#4a1015",
    "gradientTo": "#140305",
    "four": 12.54,
    "five": 12.54,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 6.54,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 75
  },
  {
    "id": "spiderman-miles",
    "name": "Spider-Man: Miles Morales",
    "sub": "مغامرات الشتاء • قوى الكهرباء والتخفي مع مايلز",
    "image": "/games/spiderman-miles.jpg",
    "gradientFrom": "#381028",
    "gradientTo": "#10030a",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 76
  },
  {
    "id": "split-fiction",
    "name": "Split Fiction",
    "sub": "أكشن ومغامرات خيال علمي • تجربة سينمائية فريدة",
    "image": "/games/split-fiction.jpg",
    "gradientFrom": "#1a2c3a",
    "gradientTo": "#060e14",
    "four": null,
    "five": 28.43,
    "secondary": 20.95,
    "costFour": null,
    "costFive": 22.43,
    "costSecondary": 14.95,
    "available": true,
    "bestSeller": false,
    "order": 77
  },
  {
    "id": "stray",
    "name": "Stray",
    "sub": "مغامرات وألغاز • استكشف مدينة السايبربانك كقطة لطيفة",
    "image": "/games/stray.jpg",
    "gradientFrom": "#382510",
    "gradientTo": "#120a03",
    "four": 12.54,
    "five": 16.28,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 10.28,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": false,
    "order": 78
  },
  {
    "id": "tekken7",
    "name": "Tekken 7",
    "sub": "قتال كلاسيكي • صراع عائلة ميشيما التاريخي",
    "image": "/games/tekken7.jpg",
    "gradientFrom": "#3a1510",
    "gradientTo": "#120403",
    "four": 10.67,
    "five": 11.61,
    "secondary": 8.8,
    "costFour": 4.67,
    "costFive": 5.61,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 79
  },
  {
    "id": "tekken8",
    "name": "TEKKEN 8",
    "sub": "الجيل القادم من القتال • رسومات Unreal Engine 5 الخارقة",
    "image": "/games/tekken8.jpg",
    "gradientFrom": "#401018",
    "gradientTo": "#140206",
    "four": null,
    "five": 20.02,
    "secondary": 14.41,
    "costFour": null,
    "costFive": 14.02,
    "costSecondary": 8.41,
    "available": true,
    "bestSeller": true,
    "order": 80
  },
  {
    "id": "witcher3",
    "name": "The Witcher 3: Complete Edition",
    "sub": "عالم مفتوح RPG • النسخة الكاملة مع الإضافات الأسطورية",
    "image": "/games/witcher3.jpg",
    "gradientFrom": "#2d2012",
    "gradientTo": "#0d0803",
    "four": 9.74,
    "five": 12.54,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 6.54,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": true,
    "order": 81
  },
  {
    "id": "tomb-raider",
    "name": "Tomb Raider: Definitive Survivor Trilogy",
    "sub": "مغامرات وآثار • ثلاثية لارا كروفت الكاملة",
    "image": "/games/tomb-raider.jpg",
    "gradientFrom": "#1d2820",
    "gradientTo": "#070c08",
    "four": 9.74,
    "five": 9.74,
    "secondary": 8.8,
    "costFour": 3.74,
    "costFive": 3.74,
    "costSecondary": 2.8,
    "available": true,
    "bestSeller": false,
    "order": 82
  },
  {
    "id": "ufc5",
    "name": "EA Sports UFC 5",
    "sub": "فنون القتال المختلطة MMA • واقعية ودقة ضربات فائقة",
    "image": "/games/ufc5.jpg",
    "gradientFrom": "#381810",
    "gradientTo": "#120603",
    "four": null,
    "five": 16.28,
    "secondary": 14.41,
    "costFour": null,
    "costFive": 10.28,
    "costSecondary": 8.41,
    "available": true,
    "bestSeller": false,
    "order": 83
  },
  {
    "id": "uncharted4",
    "name": "Uncharted 4: A Thief's End (Bundle)",
    "sub": "كنوز ومغامرات سنمائية • رحلة ناثان دريك الأخيرة",
    "image": "/games/uncharted4.jpg",
    "gradientFrom": "#1f3025",
    "gradientTo": "#07100a",
    "four": 12.54,
    "five": 14.41,
    "secondary": 10.67,
    "costFour": 6.54,
    "costFive": 8.41,
    "costSecondary": 4.67,
    "available": true,
    "bestSeller": true,
    "order": 84
  },
  {
    "id": "wwe26",
    "name": "WWE 2K26 Standard",
    "sub": "المصارعة الحرة • أحدث نجوم الحلبات وأطوار اللعب",
    "image": "/games/wwe26.jpg",
    "gradientFrom": "#3a1a1a",
    "gradientTo": "#0e0405",
    "four": null,
    "five": 39.64,
    "secondary": 30.3,
    "costFour": null,
    "costFive": 33.64,
    "costSecondary": 24.3,
    "available": true,
    "bestSeller": false,
    "order": 85
  }
];

export const DEFAULT_BUNDLES = [
  {
    id: "action-pack",
    title: "باقة الأكشن الأسطورية",
    subtitle: "GTA V + Call of Duty: Black Ops 7",
    discountPercent: 15,
    badge: "الأكثر طلباً",
    games: ["gta5", "blackops7"]
  }
];

export const DEFAULT_REVIEWS = [
  { id: 1, name: "محمد العتيبي", rating: 5, comment: "خدمة سريعة جداً وتم تفعيل حساب البلس خلال 10 دقائق!", date: "قبل يومين", order: 1 }
];

export const DEFAULT_FAQS = [
  { id: 1, q: "كيف يتم تسليم الحساب بعد الشراء؟", a: "يصلك الحساب مباشرة عبر الواتساب أو الإيميل مع خطوات التفعيل بالتفصيل.", order: 1 }
];

export const DEFAULT_SECTIONS = [
  { id: "gamelaunch", name: "قسم إطلاق الألعاب (Vice City / FC 27)", visible: true },
  { id: "recommender", name: "مساعد اختيار الاشتراك Smart Wizard", visible: true },
  { id: "essential", name: "باقة بلايستيشن بلس أساسي (Essential)", visible: true },
  { id: "extra", name: "باقة بلايستيشن بلس إكسترا (Extra)", visible: true },
  { id: "deluxe", name: "باقة بلايستيشن بلس فاخر (Deluxe)", visible: true },
  { id: "games", name: "متجر الألعاب الرقمية Games Grid", visible: true },
  { id: "reviews", name: "تقييمات وآراء العملاء", visible: true },
  { id: "faq", name: "الأسئلة الشائعة", visible: true }
];

export const DEFAULT_PROMO = {
  enabled: true,
  activeBanner: "default",
  customText: "⚡ عرض خاص: خصم 10% عند الشراء اليوم كود الخصم: DUKKANK10",
  headerBanner: {
    enabled: true,
    title: "🔥 خصم 15% بمناسبة عطلة نهاية الأسبوع!",
    code: "DUKKANK15",
    badge: "عرض خاص",
    buttonText: "تسوّق الآن",
    bgColor: "amber"
  },
  flashSale: {
    enabled: false,
    title: "⚡ عروض الفلاش السريعة — تنتهي قريباً!",
    subtitle: "احصل على خصم 20% على جميع ألعاب البلايستيشن واشتراكات بلس",
    code: "FLASH20",
    discount: 20,
    endTime: new Date(Date.now() + 86400000 * 2).toISOString(),
    badge: "ساعات محددة ⏳"
  },
  popupModal: {
    enabled: false,
    title: "🎁 هدية خاصة لزيارتك الأولى!",
    description: "احصل على خصم 10% فوري على طلبتك الأولى بمتجر دُكانك 🎮",
    code: "WELCOME10",
    discount: 10,
    buttonText: "تفعيل الخصم 🚀",
    delaySeconds: 3
  },
  applePayNotice: {
    enabled: true,
    title: "تنبيه الدفع السريع عبر Apple Pay ",
    subtitle: "للدفع المباشر السلس عبر Apple Pay، يرجى فتح المتجر في متصفح Safari.",
    buttonText: "📋 نسخ رابط المتجر لـ Safari"
  },
  socialProof: {
    enabled: true
  }
};

export const DEFAULT_SOCIAL_PROOF = {
  enabled: true,
  intervalSeconds: 12,
  items: [
    { customer: "أحمد الماجد (عمان)", text: "اشترى اشتراك بلايستيشن بلس إكسترا — سنة كاملة", time: "قبل 3 دقائق" }
  ]
};

export const DEFAULT_WA_TEMPLATES = {
  quickInquiry: "مرحباً دُكانك 🎮 أريد الاستفسار عن الألعاب والاشتراكات المتوفرة.",
  gameOrder: "مرحباً دُكانك 🎮 أريد شراء لعبة {{gameName}} على منصة {{platform}} بسعر {{price}}.",
  subOrder: "مرحباً دُكانك 🎮 أريد شراء {{subTitle}} بسعر {{price}}."
};

export const DEFAULT_CONTENT = {
  hero: {
    badge: "🔥 الموزع المعتمد الموثوق للألعاب والاشتراكات في الوطن العربي",
    title: "عالمك الأسطوري للألعاب والاشتراكات الرقمية",
    subtitle: "اشتراكات PlayStation Plus وألعاب رقمية أصلية بأفضل الأسعار، مع تسليم فوري ودعم مباشر على واتساب.",
  }
};

export const DEFAULT_SITE_SETTINGS = {
  maintenanceMode: { enabled: false, title: "الموقع قيد الصيانة", message: "نعمل على تحديثات جديدة لخدمتكم بشكل أفضل.", estimatedReturn: "ساعة واحدة" },
  disableTextSelection: false,
};

export const DEFAULT_LAUNCH_ANNOUNCEMENT = {
  enabled: true,
  theme: "vice",
  gameName: "Grand Theft Auto VI",
  badge: "🔥 الإصدار الأضخم في تاريخ الألعاب",
  subtitle: "عيش تجربة فايس سيتي بالكامل — عالم مفتوح بلا حدود مع Rockstar Games",
  description: "احصل على حسابك الأصلي المضمون لأضخم لعبة في تاريخ صناعة الألعاب. Grand Theft Auto VI يأخذك في رحلة ملحمية داخل مدينة فايس سيتي المعاد بناؤها بالكامل مع رسومات الجيل القادم وعالم حي يتنفس. تسليم فوري مع ضمان ذهبي شامل.",
  price5: 45.0,
  price4: 28.0,
  ctaLabel: "احجز نسختك الآن 🔥",
  ctaHref: "#games",
  image: "",
  imageUrl: "",
  bonusGift: "🎁 ضمان ذهبي مدى الحياة + GTA Online مجاناً + شحن $500,000 داخل اللعبة",
  rating: "⭐ الأكثر انتظاراً في تاريخ الألعاب • 🏆 Rockstar Games",
  stockLeft: 12,
  trailerUrl: "https://www.youtube.com/embed/QdBZY2fkU-0",
  countdownTarget: "2026-10-28",
  launchDate: "2026-10-28",
  note: "⚠️ الطلب المسبق يضمن لك أولوية التسليم فور الإطلاق الرسمي",
  currency: "$",
  platform5: "PS5",
  platform4: "PS4"
};

export const DEFAULT_COUPONS = [
  { id: "dukkank10", code: "DUKKANK10", discount_type: "percentage", discount_value: 10, max_uses: 100, current_uses: 12, is_active: true }
];

// Active State Cache
export let store = { ...DEFAULT_STORE };
export let subscriptions = [...DEFAULT_SUBSCRIPTIONS];
export let games = [...DEFAULT_GAMES];
export let bundles = [...DEFAULT_BUNDLES];
export let reviews = [...DEFAULT_REVIEWS];
export let faqs = [...DEFAULT_FAQS];
export let sections = [...DEFAULT_SECTIONS];
export let promo = { ...DEFAULT_PROMO };
export let socialProof = { ...DEFAULT_SOCIAL_PROOF };
export let waTemplates = { ...DEFAULT_WA_TEMPLATES };
export let content = { ...DEFAULT_CONTENT };
export let siteSettings = { ...DEFAULT_SITE_SETTINGS };
export let launchAnnouncement = { ...DEFAULT_LAUNCH_ANNOUNCEMENT };
export let coupons = [...DEFAULT_COUPONS];

export async function initStoreDb() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS store_config (
        key        VARCHAR(100) PRIMARY KEY,
        value      JSONB NOT NULL,
        updated_at TIMESTAMPTZ DEFAULT NOW()
      )
    `);

    [
      store, subscriptions, games, bundles, reviews, faqs,
      sections, promo, socialProof, waTemplates, content,
      siteSettings, launchAnnouncement, coupons
    ] = await Promise.all([
      dbLoad("store",              DEFAULT_STORE),
      dbLoad("subscriptions",      DEFAULT_SUBSCRIPTIONS),
      dbLoad("games",              DEFAULT_GAMES),
      dbLoad("bundles",            DEFAULT_BUNDLES),
      dbLoad("reviews",            DEFAULT_REVIEWS),
      dbLoad("faqs",               DEFAULT_FAQS),
      dbLoad("sections",           DEFAULT_SECTIONS),
      dbLoad("promo",              DEFAULT_PROMO),
      dbLoad("socialProof",        DEFAULT_SOCIAL_PROOF),
      dbLoad("waTemplates",        DEFAULT_WA_TEMPLATES),
      dbLoad("content",            DEFAULT_CONTENT),
      dbLoad("siteSettings",       DEFAULT_SITE_SETTINGS),
      dbLoad("launchAnnouncement", DEFAULT_LAUNCH_ANNOUNCEMENT),
      dbLoad("coupons",            DEFAULT_COUPONS),
    ]);
  } catch (_) {}
}

initStoreDb();
